config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja|vi/ do
    root "static_pages#home"
    get "help" => "static_pages#help"
    get "signup" => "users#new"
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
    resources :users
    resources :relationships, only: [:create, :destroy]
    resources :categories, only: [:index]
    namespace :admin do
      root "users#index"
      resources :users, except: [:new, :create, :edit]
      resources :words, except: [:new, :show, :destroy]
    end
    resources :lessons, except: [:new, :create, :destroy]
    resources :categories do
      resources :lessons, only: :create
      resources :words, only: :index
    end
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: :home
  
  def home
    @activities = current_user.activities.paginate page: params[:page],
      per_page: 30
    respond_to :html, :js
  end

  def help
    @users = User.all_admin
  end
end

app/views/static_pages/help.html.erb
<h3><%= t ".h3" %></h3>
<%= render @users %>

app/views/static_pages/home.html.erb
<div class="row">
    <div class="span4">
        <div class="profile-box profile-view">
            <div class="thumb">
                <%= link_to gravatar_for(current_user, size: 140), current_user %>
            </div>
            <div class="text">
                <p>Welcome</p>
                <a href="#" class="btn-style"><%= current_user.name %></a>
            </div>
        </div>
        <div class="profile-box edit-profile">
            <h2>Learning Area</h2>
            <ul>
                <li><%= link_to 'Categories', categories_path %></li>
                <li><%= link_to 'Lessons', lessons_path %></li>
            </ul>
        </div>
    </div>
    <div class="span8">
        <div class="sidebar">
            <div class="widget widget-papular-post">
                <ul id="activities">
                    <%= render @activities %>
                </ul>
                <div id="scroll">
                    <%= will_paginate @activities %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/home.js.erb
$("#activities").append("<%= j render @activities %>");
<% if @activities.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate @activities %>");
<% else %>
  $(window).off("scroll");
  $(".pagination").remove();
<% end %>