config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja|vi/ do
    root "static_pages#home"
    get "help" => "static_pages#help"
    get "signup" => "users#new"
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
    resources :users
    resources :relationships, only: [:create, :destroy]
    resources :categories, only: [:index]
    namespace :admin do
      root "users#index"
      resources :users, except: [:new, :create, :edit]
      resources :words, except: [:new, :show, :destroy]
    end
    resources :lessons, except: [:new, :create, :destroy]
    resources :categories do
      resources :lessons, only: :create
      resources :words, only: :index
    end
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  enum role: [:normal, :admin, :teacher]

  before_save ->{self.email = email.downcase}
  before_create :default_role

  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :results, through: :lessons

  has_many :following_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :delete_all
  has_many :followers_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :delete_all

  has_many :following, through: :following_relationships, source: :followed
  has_many :followers, through: :followers_relationships, source: :follower

  has_secure_password

  validates :email,
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
    presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
  validates :password, allow_nil: true,
    length: {minimum: 5}
  validates :name, presence: true,
    length: {maximum: 50}
  scope :search, ->query{where "name LIKE ? OR email LIKE ?", "%#{query}%", "%#{query}%"}
  scope :all_admin, ->{where "role = 1"}

  def User.digest string
    cost = if ActiveModel::SecurePassword.min_cost
      BCrypt::Engine::MIN_COST
    else
      BCrypt::Engine.cost
    end
    BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password? remember_token
  end

  def forget
    update_attributes remember_digest: nil
  end

  def follow other_user
    following_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def default_role
    self.role = :normal
  end

  def block
    update_attributes blocked_at: Time.now
  end

  def unblock
    update_attributes blocked_at: nil
  end

  def blocked?
    !self.blocked_at.nil?
  end

  def update_role new_role
    update_attributes role: new_role
  end

  def reset_password
    update_attributes password_digest: User.digest(Settings.user.default_password)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_user, only: [:destroy, :update, :show]

  def index
    if params[:search]
      @users = User.search(params[:search])
        .paginate page: params[:page], per_page: 10
    else
      @users = User.paginate page: params[:page], per_page: 10
    end
  end

  def update
    if params[:admin_action] == "block"
      action_block
    elsif params[:admin_action] == "edit_role"
      action_edit_role
    elsif params[:admin_action] == "reset_password"
      action_reset_password
    end
  end

  def show
    redirect_to root_path if @user.nil?
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controllers.users.destroy.flash_success"
    else
      flash[:danger] = t "controllers.users.destroy.flash_danger"
    end
    redirect_to admin_users_url
  end

  private
  def load_user
    @user = User.find params[:id] if User.exists? params[:id]
  end

  def action_block
    @user.blocked? ? @user.unblock : @user.block
    redirect_to admin_users_url
  end

  def action_edit_role
    @user = User.find params[:user_id]
    if @user.update_role params[:new_role]
      render json: {message: t("controllers.admin.users.success_edit_role")},
      status: :ok
    else
      render json: {message: t("controllers.admin.users.failed_edit_role")},
      status: :internal_server_error
    end
  end

  def action_reset_password
    if @user.reset_password
      render json: {message: t("controllers.admin.users.success_reset_password")},
      status: :ok
    else
      render json: {message: t("controllers.admin.users.failed_reset_password")},
      status: :internal_server_error
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :load_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    if params[:search]
      @users = User.search(params[:search])
        .paginate page: params[:page], per_page: 10
    else
      @users = User.paginate page: params[:page], per_page: 10
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "controllers.users.create.flash_success",
        name: @user.name
      redirect_to @user
    else
      render :new
    end
  end

  def show
    redirect_to root_path if @user.nil?
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "controllers.users.update.flash_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password, :password_confirmation
  end

  def correct_user
    redirect_to root_url unless current_user? @user
  end

  def load_user
    @user = User.find params[:id] if User.exists? params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 50}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = Settings.user.gavatar_url + "#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.following_relationships.build, remote: true do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user? @user %>
  <div id="follow_form">
    <%= render current_user.following?(@user) ? "users/unfollow" : "users/follow" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-body">
    <%= render "shared/error_messages" %>
    <fieldset>
        <%= f.label :name, t(".name") %>
        <%= f.text_field :name, class: "input-block-level" %>
        <%= f.label :email, t(".email") %>
        <%= f.email_field :email, class: "input-block-level" %>
        <%= f.label :password, t(".password") %>
        <%= f.password_field :password, class: "input-block-level" %>
        <%= f.label :password_confirmation, t(".confirmation") %>
        <%= f.password_field :password_confirmation, class: "input-block-level" %>
        <%= f.submit t(".btn_submit_#{controller.action_name}"), class: "btn-style", id: "btn-signup" %>
    </fieldset>
    </div>
<% end %>

app/views/users/_index.html.erb
<h1><%= t ".h1index" %></h1>
<%= will_paginate %>
<div>
  <%= render "users/search" %>
</div>
<div class="tab-content container">
  <div class="tab-pane fade active in" id="web">
    <ul class="course-topics row">
		  <% if @users.present? %>
		    <%= render @users %>
		  <% else %>
		    <p><%= t ".no_result", result: params[:search] %>.</p>
		  <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/_search.html.erb
<% if current_user.admin? %>
  <%= form_tag admin_users_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: t(".placeholder") %>
    <%= submit_tag t ".btn_search" %>
  <% end %>
<% else %>
  <%= form_tag users_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: t(".placeholder") %>
    <%= submit_tag t ".btn_search" %>
  <% end %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.following_relationships.find_by(followed_id: @user.id),
  remote: true,
  html: {method: :delete} do |f| %>
  <%= f.submit t(".submit"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li class="span4">
	<div class="thumb">
		<%= link_to gravatar_for(user, size: 133), user_path(user) %>
	</div>
	<div class="text">
		<h4><%= link_to user.name, user_path(user) %></h4>
	    <p><%= user.email %></p>
	</div>
</li>

app/views/users/edit.html.erb
<h1><%= t ".edit" %></h1>
<div class="row">
  <div class="form-box offset3 span6">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<%= render "users/index" %>

app/views/users/new.html.erb
<h1><%= t ".signup" %></h1>
<div class="row">
  <div class="form-box offset3 span6">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4 user_info center jumbotron">
    <section class="user_info">
      <aside class="col-md-4">
        <%= render @user %>
        <%= render "follow_form" if logged_in? %>
      </aside>
    </section>
    <section class="stat">
      <%= render "shared/stats" %>
    </section>
  </aside>
</div>