config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja|vi/ do
    root "static_pages#home"
    get "help" => "static_pages#help"
    get "signup" => "users#new"
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
    resources :users
    resources :relationships, only: [:create, :destroy]
    resources :categories, only: [:index]
    namespace :admin do
      root "users#index"
      resources :users, except: [:new, :create, :edit]
      resources :words, except: [:new, :show, :destroy]
    end
    resources :lessons, except: [:new, :create, :destroy]
    resources :categories do
      resources :lessons, only: :create
      resources :words, only: :index
    end
  end  
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  include ActivityLog
  after_update :create_finish_lesson_log
  
  belongs_to :user
  belongs_to :category

  has_many :results, dependent: :destroy
  has_many :words, through: :results
  has_many :answers, through: :results
  has_many :activities, as: :targetable

  accepts_nested_attributes_for :results

  before_create lambda {
    words = self.category.words.order("RANDOM()").limit 20
    self.words = words
  }

  def finished?
    !self.mark.nil?
  end

  def create_finish_lesson_log
    unless finished?
      create_log self, self.user_id, Settings.activity_type.take_lesson
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user
  before_action :current_lesson, except: [:index, :create]
  before_action :correct_user, except: [:index, :create]
  before_action :finished?, only: [:edit, :update]

  def index
    @lessons = current_user.lessons
      .paginate page: params[:page], per_page: 10
  end

  def create
    category = Category.find params[:category_id]
    @lesson = category.lessons.build user: current_user
    if @lesson.save
      redirect_to @lesson
    else
      flash[:danger] = t "controllers.lessons.create.flash_danger"
      redirect_to root_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @lesson.update_attributes lesson_params
      @lesson.mark = @lesson.results.correct_answer.count
      @lesson.save
      redirect_to @lesson
    else
      render :edit
    end
  end

  private
  def current_lesson
    @lesson = Lesson.find params[:id]
  end

  def correct_user
    unless current_user == @lesson.user
      redirect_to root_path
    end
  end
  
  def lesson_params
    params.require(:lesson).permit results_attributes: [:id, :answer_id]
  end

  def finished?
    unless @lesson.mark.nil?
      flash[:danger] = t "controllers.lessons.already_done"
      redirect_to lessons_path
    end
  end
end

app/views/lessons/_lesson.html.erb
<tr>
  <td>
    <%= lesson.category.name %>
  </td>
  <td><%= lesson.results.answered.count %>
      <%= t ".question_done" %>
  </td>
  <td>
    <%= lesson.created_at.to_formatted_s :short %>
  </td>
  <td>
      <% unless lesson.finished? %>
        <div class="col-md-4">
          <%= button_to t(".take_lesson"), edit_lesson_path(lesson), method: :get, class: "btn btn-default" %>
        </div>
      <% else %>
        <div class="col-md-4">
          <%= link_to(lesson_path(lesson)) do %>
            <%= lesson.mark %>
            <%= t ".slash" %>
            <%= lesson.results.count %>
          <% end %>
          <%#= lesson.mark %>
          <%#= t ".slash" %>
          <%#= lesson.results.count %>
        </div>
    <% end %>
  </td>
</tr>

app/views/lessons/edit.html.erb
<%= form_for @lesson do |f| %>
  <%= f.fields_for :results do |builder| %>
    <div class="row question">
      <div class="col-md-4">        
        <h3>
          <%= builder.options[:child_index] + 1 %>.
          <%= builder.object.word.content %>
        </h3>
      </div>
      <div class="col-md-8 container-fluid">
        <% builder.object.word.answers.suffer.each do |answer| %>
          <div class="row">
            <%= builder.radio_button :answer_id, answer.id %>
            <%= answer.content %>
          </div>
          <hr>
        <% end %>
      </div>
      <hr>
    </div>
  <% end %>
  <div class="row">
    <%= f.submit t(".submit"), class: "col-md-2 btn btn-primary", id: "submit_test" %>
  </div>
<% end %>

app/views/lessons/index.html.erb
<h3 class="row">
  <%= t ".all_lesson" %>
</h3>
<div class="event-vanue">
    <table>
        <div class="row", id="word_list">
          <tr>
            <td>
              <%= t ".lesson_category_name" %>
            </td>
            <td>
              <%= t ".lesson_results_answered" %>
            </td>
            <td>
              <%= t ".lesson_create_time" %>
            </td>
            <td>
              <%= t ".lesson_mark" %>
            </td>
          </tr>
            <%= render @lessons %>
            <%= will_paginate @lessons %>
        </div>
    </table>
</div>

app/views/lessons/show.html.erb
<h3 class="row">
  <%= t ".all_lesson" %>
</h3>

<div class="event-vanue">
    <table>
        <div class="row", id="word_list">
          <tr>
            <td>
              <%= t ".lesson_category_name" %>
            </td>
            <td>
              <%= t ".lesson_results_answered" %>
            </td>
            <td>
              <%= t ".lesson_create_time" %>
            </td>
            <td>
              <%= t ".lesson_mark" %>
            </td>
          </tr>
            <%= render @lesson %>
        </div>
    </table>
</div>
<% if @lesson.finished? %>
  <div class="row">
    <% @lesson.results.each_with_index do |result, index| %>
      <div class="col-md-4 question" >
        <%= index + 1 %>.&nbsp
        <%= result.word.content %>  
      </div>
      <div class= "col-md-8">
        <% if result.correct? %>
          <div style="background-color: #ccffcc; padding: 10px; ">
            <%= result.answer.content %>
          </div>
        <% else %>
          <div style="background-color: #ffe6e6; padding: 10px;">
            <%= t ".false_result" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>