config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|ja|vi/ do
    root "static_pages#home"
    get "help" => "static_pages#help"
    get "signup" => "users#new"
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
    resources :users
    resources :relationships, only: [:create, :destroy]
    resources :categories, only: [:index]
    namespace :admin do
      root "users#index"
      resources :users, except: [:new, :create, :edit]
      resources :words, except: [:new, :show, :destroy]
    end
    resources :lessons, except: [:new, :create, :destroy]
    resources :categories do
      resources :lessons, only: :create
      resources :words, only: :index
    end
  end  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: :index

  def index
    @categories = Category.all.paginate page: params[:page],
      per_page: 10
  end
end

app/views/categories/_category.html.erb
<% if category_counter % 3 == 0 %>
<div class="row">
<% end %>
    <div class="span4">
        <div class="course">
            <div class="text">
                <div class="header">
                    <h4><%= category.name %></h4>
                    <div class="rating">
                        <span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
                    </div>
                </div>
                <div class="course-name">
                    <p><%= category.description %></p>
                </div>
                <div class="course-detail-btn">
                    <%= form_for [category, category.lessons.build] do |f| %>
                        <%= f.submit t(".btn_take"), class: "btn-style" %>
                    <% end %>
                    <%= button_to t(".btn_gotoword"), category_words_path(category), method: :get, class: "btn-style" %>
                </div>
            </div>
        </div>
    </div>
<% if category_counter % 3 == 2 %>
</div>
<% end %>

app/views/categories/index.html.erb
<h2 class="row">
  <%= t ".title" %>
</h2>
<%= render @categories %>
<%= will_paginate @categories %>